language: generic
dist: bionic
python:
  - "3.8"
node_js:
  - "13.12.0"
install:
  - sudo chown -R travis:travis /home/travis/
  - bash ./install.sh
script:
  - echo "Test not implemented yet"
deploy:
  provider: heroku
  api_key: '$HEROKU_AUTH_TOKEN'
  cleanup: false # So Travis does not deleted the generated requirements.txt
  run:
    - sudo chown -R travis:travis /home/travis/
    - bash ./after_deploy.sh
  app:
    master: twilio-dev-hackathon
    develop: twilio-dev-hackathon-dev
