language: python
python:
  - "3.8"
node_js:
  - "node"
install:
  - pip install poetry
  - poetry export -f requirements.txt > requirements.txt
  - pip install -r requirements.txt
script:
  - echo "Test not implemented yet"
deploy:
  provider: heroku
  api_key: '$HEROKU_AUTH_TOKEN'
  cleanup: false # So Travis does not deleted the generated requirements.txt
  run:
    - sudo apt install nodejs
    - sudo apt install npm
    - bash ./after_deploy.sh
  app:
    master: twilio-dev-hackathon
    develop: twilio-dev-hackathon-dev
